### ISSUE TITLE
 Webpack - Did you forget to signal async completion?

### ISSUE THREAD

**Issue by media-store-net** [10quality/wpmvc#22]
Hi @all, i'm try out your framework in one of my plugins. The Framework itself is very helpfull, thanks for that, great Job.
I get this message on gulp compilation with gulp dev,  but only if the webpack.config.js is present.

`[07:21:37] The following tasks did not complete: dev, scripts, webpack, webpackPromise
[07:21:37] Did you forget to signal async completion?`

Without the webpack.config.js it runs well. 
Npm run webpack without arguments is also ok. When i use --hide-modules instead, i got a error
`[webpack-cli] Error: Unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options
`
Here is the part of my dependencies in the package.json
`"dependencies": {
    "axios": "^0.21.1",
    "bootstrap-icons": "^1.9.1",
    "gulp": "4.0.2",
    "gulp-wpmvc": "^1.3.*",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "bootstrap": "^4.6.2",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  },`

Webpack Configuration
`
const path = require('path');

module.exports = {
	mode: 'development',
	entry: {
		'admin': './assets/raw/js/admin/index.js',
		'app': './assets/raw/js/main.js',
	},
	output: {
		filename: '[name].js',
		path: path.resolve( __dirname, 'assets/js' ),
		publicPath: './assets/js',
	},
	target: 'web'
};
`

and here is the gulpfile.js
`
// --------------
// START - CUSTOM TASKS

gulp.task('vendorcss', async function () {
	return gulp.src([
		'./node_modules/bootstrap-icons/font/bootstrap-icons.css',
	])
		.pipe(gulp.dest('./assets/css'));
});

gulp.task('vendorjs', async function () {
	return gulp.src([
		'./node_modules/vue/dist/vue.global.js',
		'./node_modules/axios/dist/axios.min.js',
	])
		.pipe(gulp.dest('./assets/js'));
});

config.prescripts = ['vendorcss', 'vendorjs'];

// END - CUSTOM TASKS
`

All of the Setting comes from your documentation.
Do you have any idea how i can fix the async completion? It is a bug or should i use maybe one of other webpack versions?

**Comment by amostajo** [comment]
Please follow https://www.wordpress-mvc.com/2021/09/05/using-vue-js/ step by step.
