### ISSUE TITLE
How to setup Relationships in model?

### ISSUE THREAD

**Issue by bipinbheda** [10quality/wpmvc#23]
Is there any documentation or example of a Model relationship? 

I have a user model and I want to get all the articles of the user, Is there any way to do so?

In my User model, I write this code:

public function tasks() {
    return $this->has_many(Task::class, 'post_author');
}

And accessing this in the controller like this:
$user = new User();
$user::find(2)->tasks;

But it doesn't seem to work. I am not sure what I missed.

**Comment by garretthyder** [comment]
Not sure if this works but maybe the from() method mentioned here;
https://www.wordpress-mvc.com/v1/models/post-models/
`$attachments = Attachment::from( $post->ID );`

**Comment by bipinbheda** [comment]
Nope, It did not work.

I checked this with the bellow code but it returns an empty collection Object(Even though I attached the featured image)

```
$post = Post::find( 1 );
$attachments = Attachment::from( $post->ID );
```

Result:
```
WPMVC\MVC\Collection Object
(
    [storage:ArrayObject:private] => Array
        (
        )

)
```

**Comment by amostajo** [comment]
Hi, please read this documentation: https://www.wordpress-mvc.com/v1/models/post-models/#relationships

The example indicated is incorrect as `post_author` or `post_parent` are single IDs, and the `has_many()` relationship requires the relation to be an array of multiple ids.
```php
public function tasks() {
    return $this->has_many(Task::class, 'post_author');
}
```

So the correct relationship would be to us `has_one()` or `belongs_to()`, for example:
```php
protected function task()
{
    return $this->belongs_to( Task::class, 'post_author' );
}
```

Now, if you want to use the `has_many()` the you probably want to map the relationship to an alias that can return multiple IDs, for example:
```php
protected $aliases = [
    'task_ids' => 'meta_tasks_ids',
    'user_ids' => 'func_user_ids',
];

/***
 * Handler for "func_user_ids" alias.
 */
protected function user_ids()
{
    // Here I am returning user ID 1 and 2,
    return [1,2];
}

/**
 * Correct has_many() relationship.
 */
protected function tasks()
{
   return $this->has_many( Task::class, 'task_ids' );
}

/**
 * Correct has_many() relationship.
 */
protected function users()
{
   return $this->has_many( User::class, 'user_ids' );
}
```

Now you can do:
```php
var_dump( MyModel::find( 2 )->tasks );
var_dump( MyModel::find( 2 )->users );
```
