### ISSUE TITLE
Best practice to add register_activation_hook?

### ISSUE THREAD

**Issue by galabl** [10quality/wpmvc#24]
Title question, don't really wanna have it in main plugin file.

**Comment by galabl** [comment]
Actually from what I saw it's not possible. What I did for now is to create AtcDeact class in app/ directory and than calling it from the main plugin file. If someone have better recommendation, shoot.

**Comment by last-core** [comment]
Have you managed to find a solution? I'm on the same boat and I'd like to setup a uninstall script too
