### ISSUE TITLE
Calling controller and cruds

### ISSUE THREAD

**Issue by axoloth** [10quality/wpmvc#25]
The framework is well documented but i think, some essentials thinks are missing.
I can't see some Routing feature, so, how call a simple controller's method in a view (link or button) ?

Is there any sample (or plugin project) showing how doing the CRUD of a custom model ?

Thanks!

**Comment by amostajo** [comment]
For custom model on custom data tables see this article https://github.com/10quality/wp-query-builder/wiki/Handling-A-Data-Model

**Comment by amostajo** [comment]
To access controller method directly, look at this https://www.wordpress-mvc.com/v1/main-class/#direct-mvc
