### ISSUE TITLE
Composer error with MyApp being invalid package name

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc#4]
Hello,

Following the setup instructions I ran `composer install` and got the following error;
Deprecation warning: Your package name MyApp is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

It seems Composer needs both a vendor name and package name in lowercase like;
wpmvc/my-app

**Comment by amostajo** [comment]
Before this can be added, `wpmvc-commands` package reviewed.

**Comment by amostajo** [comment]
@garretthyder changes have been made.

To migrate and support composer 2.0 and the new updates.

1) Define a text domain, which should be in lower case, no spaces and with dashes. Like `my-app`.

2) In your `composer.json` file change the name to:
```json
{
  "name": "wpmvc/my-app",
}
```

3) In your `package.json` file change the name to:
```json
{
  "name": "my-app",
}
```

4) In your `app/Config/app.php` file change the `localize > textdomain` to:
```php
    'localize' => [
        'textdomain'    => 'my-app',
    ],
```

**Comment by garretthyder** [comment]
Thanks @amostajo much appreciate the update. This is looking to fix the issue, I appreciate the quick turnaround and look forward to playing around more with ayuco, etc.
