### ISSUE TITLE
Add support for custom plugin filenaming.

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc#7]
Hi @amostajo 

I wanted your thoughts on supporting a custom plugin filename so instead of just plugin.php users can provide their plugin with pluginname.php.

It's often the convention with WP plugin development to have your main plugin loader file the same name as your plugin.

In my current copy I've renamed plugin.php but am finding it's throwing some errors on set commands as they are looking for plugin.php and not my custom filename. 

Am thinking could be implemented by adding an option to the config/app.php file with the plugin filename and if set use it for looking up the plugin file during set command replacements.

I hope that makes sense

**Comment by amostajo** [comment]
@garretthyder Sound good to have the option. Maybe we can make an optional command that does this for you, what you think?

**Comment by garretthyder** [comment]
Awesome, ya I was thinking of latching into the SetCommand something like;
`php ayuco set pluginfile:filename.php` *not sure if we need to have the .php on the filename.

**Comment by amostajo** [comment]
@garretthyder maybe we shouldn't as it will always be php.

I will add this issue to `wpmvc-commands`, you are free to do a PR if you wish.

**Comment by garretthyder** [comment]
Thanks @amostajo sounds good
