### ISSUE TITLE
Support Node >10

### ISSUE THREAD

**Issue by garretthyder** [10quality/wpmvc#8]
Hi @amostajo I got stuck on this for a while as I overlooked the requirement;
NodeJS (< v.10)

I kept hitting the node-sass@3.13.1 postinstall script issue but wasn't sure how to resolve with wpmvc. On other projects like JointsWP I was able to just bump gulp-sass in the package.json and everything was honky dory, see the bug I fixed with help on JointsWP;
https://github.com/JeremyEnglert/JointsWP/issues/317#issuecomment-365720709

For wpmvc I can't seem to do this as the dependency comes I believe from gulp-wpmvc or another loaded component and not the core.

If you could point me to where gulp-sass/node-sass is referenced as a dependancy hopefully we can resolve the NodeJS old version requirement with a simple version bump on the sass dependancy.

Thank you

**Comment by amostajo** [comment]
Moved to https://github.com/10quality/gulp-wpmvc/issues/6

**Comment by amostajo** [comment]
@garretthyder https://www.wordpress-mvc.com/2020/02/15/version-1-0-3/
